# Generated by Django 2.2.2 on 2019-06-08 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0002_auto_20190603_2036'),
        ('usuario', '0002_auto_20190607_1137'),
        ('patrocinio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinio',
            name='patrocinador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='patrocinador', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='patrocinio',
            name='viagem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='viagem', to='viagem.Viagem'),
        ),
        migrations.AlterField(
            model_name='patrocinio',
            name='data_intencao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
