# Generated by Django 2.2.1 on 2019-06-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
                ('data_ida', models.DateField()),
                ('data_volta', models.DateField()),
                ('descricao_comp', models.TextField()),
                ('modalidade_comp', models.CharField(max_length=30)),
                ('path_documento', models.FilePathField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
