# Generated by Django 2.2.1 on 2019-06-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='status',
            field=models.CharField(choices=[('1', 'EM AVALIAÇÃO'), ('2', 'ABERTO'), ('3', 'EM PATROCINIO'), ('4', 'PATROCINADA')], max_length=1),
        ),
    ]
