# Generated by Django 2.2.1 on 2019-06-07 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190607_1137'),
        ('viagem', '0002_auto_20190603_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='id_atleta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='atleta', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='id_patrocinador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='patrocinador', to='usuario.Usuario'),
        ),
    ]
