# Generated by Django 2.2.1 on 2019-06-07 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0003_auto_20190607_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viagem',
            old_name='id_atleta',
            new_name='atleta',
        ),
        migrations.RenameField(
            model_name='viagem',
            old_name='id_patrocinador',
            new_name='patrocinador',
        ),
    ]
