# Generated by Django 2.2.1 on 2019-06-08 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190607_1137'),
        ('viagem', '0005_auto_20190608_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_intencao', models.DateTimeField(auto_now_add=True)),
                ('patrocinador', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='patrocinador', to='usuario.Usuario')),
                ('viagem', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='viagem_opened', to='viagem.Viagem')),
            ],
        ),
    ]
