# Generated by Django 2.2.1 on 2019-06-08 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0006_patrocinio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinio',
            name='patrocinador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='patrocinador_opened', to='usuario.Usuario'),
        ),
    ]
