# Generated by Django 2.2.1 on 2019-06-08 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0008_auto_20190608_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinio',
            name='patreon',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='patrocinador_o', to='usuario.Usuario'),
        ),
    ]
