# Generated by Django 2.2.1 on 2019-06-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0010_auto_20190608_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patrocinio',
            old_name='patrocinador',
            new_name='patrocinadorOp',
        ),
    ]
