# Generated by Django 2.2.1 on 2019-06-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0011_auto_20190608_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='patrocinador',
        ),
        migrations.AddField(
            model_name='patrocinio',
            name='status_pat',
            field=models.CharField(choices=[('1', 'PENDENTE'), ('2', 'ENVIADO'), ('3', 'CONFIRMADO'), ('4', 'RECUSADO')], default='', max_length=1),
        ),
    ]
