# Generated by Django 2.2.1 on 2019-06-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0013_auto_20190608_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinio',
            name='ticket',
            field=models.CharField(default='', max_length=6),
        ),
    ]
