# Generated by Django 2.2.1 on 2019-06-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0014_patrocinio_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='competicao',
            field=models.CharField(default='', max_length=30),
        ),
    ]
