# Generated by Django 2.2.1 on 2019-06-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0015_viagem_competicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atleta', to='usuario.Usuario'),
        ),
    ]
